<a href="https://colab.research.google.com/github/tombackert/ml-stuff/blob/main/linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra (for Deep-Learning)

In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

### 2.1 Scalars, Vectors, Matrices and Tensors

In [ ]:
# Scalars
a1 = np.array([2])
a2 = np.array([2])
a1.T

In [20]:
# Vectors (array of numbers)
v1 = np.array([1, 2, 3])
v2 = np.array([[1],
               [2],
               [3]])

In [26]:
# Tranposing a vector
# vector = matrix with onely one column
v1, v1.T

(array([1, 2, 3]), array([1, 2, 3]))

In [25]:
v2, v2.T

(array([[1],
        [2],
        [3]]),
 array([[1, 2, 3]]))

In [29]:
# Matrix (2-D array of numbers)
A = np.array([[2, 2],
              [3, 3],
              [4, 4]])

B = np.array([[2, 2, 2],
              [3, 3, 3]])

A, B

(array([[2, 2],
        [3, 3],
        [4, 4]]),
 array([[2, 2, 2],
        [3, 3, 3]]))

In [31]:
# Transposing a matrix (Mirror image across the main diagonal line)
A.T, B.T

(array([[2, 3, 4],
        [2, 3, 4]]),
 array([[2, 3],
        [2, 3],
        [2, 3]]))

In [38]:
# matrices with shape (3, 3)
A = np.array([[1, 1, 1],
              [1, 1, 1],
              [1, 1, 1]])

B = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B2 = np.array([[1, 1, 1],
               [2, 2, 2],
               [3, 3, 3]])

In [39]:
# Adding matrices
C = A + B
C

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [41]:
a1 = np.array([2])
a2 = np.array([3])

In [47]:
# adding or multiplying a matrix by a scaler
D1 = a1 * A + a2
D2 = a1 * B2 + a2
D1, D2

(array([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]]),
 array([[5, 5, 5],
        [7, 7, 7],
        [9, 9, 9]]))

#### Take aways
- vector = matrix containing only one column
- transpose of a vector -> matrix with only one row
- scalar = matrix with only one entry
- scalar is its own transpose


### 2.2 Multiplying Matrices and Vectors

In [60]:
x = np.array([1, 1, 1])

y1 = np.array([1, 4, 7])
y2 = np.array([2, 5, 8])

In [61]:
# element-wise product
element_wise_product1 = x * y1
element_wise_product2 = y1 * y2
element_wise_product1, element_wise_product2

(array([1, 4, 7]), array([ 2, 20, 56]))

In [62]:
# dot product
dot_product1 = np.dot(x, y1)
dot_product2 = np.dot(x, y2)

dot_product1, dot_product2

(12, 15)

In [54]:
dp1 = x @ y1
dp2 = x @ y2
dp1, dp2

(12, 15)

In [65]:
# Multiplying Matrices and Vectors
E3 = np.array([[1, 0, 0],
               [0, 1, 0],
               [0, 0, 1]])

E0 = np.array([[1, 1, 1],
               [1, 1, 1],
               [1, 1, 1]])

#3 x 3

A1 = np.array([[2, 2, 2],
               [2, 2, 2],
               [2, 2, 2]])

B1 = np.array([[1, 1, 1],
               [2, 2, 2],
               [3, 3, 3]])

B2 = np.array([[2, 3, 4],
               [2, 3, 4],
               [2, 3, 4]])

B3 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])


In [66]:
# Element-wise product
D1 = A1 * B1
D2 = E3 * A1
D3 = B1 * B3
D1, D2, D3

(array([[2, 2, 2],
        [4, 4, 4],
        [6, 6, 6]]),
 array([[2, 0, 0],
        [0, 2, 0],
        [0, 0, 2]]),
 array([[ 1,  2,  3],
        [ 8, 10, 12],
        [21, 24, 27]]))

In [70]:
# matrix product = dot product for every element
D1 = A1 @ B1
D2 = E3 @ A1
D3 = B1 @ B3
D1, D2, D3

(array([[12, 12, 12],
        [12, 12, 12],
        [12, 12, 12]]),
 array([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]),
 array([[12, 15, 18],
        [24, 30, 36],
        [36, 45, 54]]))

In [84]:
# Multipling matrices of different shape
#2 x 3
A1 = np.array([[1, 2, 3],
               [4, 5, 6]])

#3 x 3
A2 = np.array([[3, 3, 3],
               [3, 3, 3],
               [3, 3, 3]])

#3 x 2
B1 = np.array([[2, 2],
               [2, 2],
               [2, 2]])

#2 x 2
B2 = np.array([[1, 2],
               [4, 5]])

In [77]:
# m x n @ n x p -> m x p
C = A2 @ B1 # 3 x 3 @ 3 x 2 -> 3 x 2
C

array([[36, 45],
       [36, 45],
       [36, 45]])

In [86]:
C1 = B1 @ B2 # 3 x 2 @ 2 x 2 -> 3 x 2
C2 = B2 @ A1 # 2 x 2 @ 2 x 3 -> 2 x 3
C3 = B1 @ A1 # 3 x 2 @ 2 x 3 -> 3 x 3
C1, C2, C3

(array([[10, 14],
        [10, 14],
        [10, 14]]),
 array([[ 9, 12, 15],
        [24, 33, 42]]),
 array([[10, 14, 18],
        [10, 14, 18],
        [10, 14, 18]]))

In [89]:
#3 x 3
A1 = np.array([[2, 2, 2],
               [2, 2, 2],
               [2, 2, 2]])

A2 = np.array([[1, 1, 1],
               [2, 2, 2],
               [3, 3, 3]])

B1 = np.array([[2, 3, 4],
               [2, 3, 4],
               [2, 3, 4]])

B2 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])

In [90]:
# matrix mul is distributive
D1 = A1 @ (B1 + B2)
D2 = A1 @ B1 + A1 @ B2
D1, D2

(array([[36, 48, 60],
        [36, 48, 60],
        [36, 48, 60]]),
 array([[36, 48, 60],
        [36, 48, 60],
        [36, 48, 60]]))

In [91]:
# matrix mul is associative
D1 = A2 @ (B1 @ B2)
D2 = (A2 @ B1) @ B2
D1, D2

(array([[126, 153, 180],
        [252, 306, 360],
        [378, 459, 540]]),
 array([[126, 153, 180],
        [252, 306, 360],
        [378, 459, 540]]))

In [92]:
# matrix mul is not commutative
D1 = A1 @ A2
D2 = A2 @ A1
D1, D2

(array([[12, 12, 12],
        [12, 12, 12],
        [12, 12, 12]]),
 array([[ 6,  6,  6],
        [12, 12, 12],
        [18, 18, 18]]))

In [108]:
v1 = np.array([1, 2, 3])
v2 = np.array([3, 3, 3])
v3 = np.array([[2],
               [2],
               [2]])
v2.T.shape, v2.shape, v3.shape

((3,), (3,), (3, 1))

In [112]:
# product between vectors is commutativ
d1 = v1.T @ v2 # 1 x 3 @ 3 x 1 -> 1 x 1
d2 = v2.T @ v1 # 1 x 3 @ 3 x 1 -> 1 x 1
d1, d2

(18, 18)

In [95]:
# Transpose of a matrix product
T1 = (A1 @ B1).T
T2 = B1.T @ A1.T
T1, T2

(array([[12, 12, 12],
        [18, 18, 18],
        [24, 24, 24]]),
 array([[12, 12, 12],
        [18, 18, 18],
        [24, 24, 24]]))

### 2.3 Identiy and Inverse Matrices

In [ ]:
# Identity and Inverse Matrix
D = np.array([[1, 0, 0],
              [0, 2, 0],
              [0, 0, 4]])

In [ ]:
# determinat
det_D = np.linalg.det(D)
det_D

7.999999999999998

In [ ]:
# inverse
D_inv = np.linalg.inv(D)
D_inv

array([[1.  , 0.  , 0.  ],
       [0.  , 0.5 , 0.  ],
       [0.  , 0.  , 0.25]])

In [ ]:
# D_inv @ D -> I
I = D_inv @ D
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# linear dependency
B = np.matrix([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
B.shape

(3, 3)

In [ ]:
# A matrix is considered to have linearly dependent rows if its rank is less than the number of rows.
np.linalg.matrix_rank(B) # rank of B is 2 < number of rows -> linear dependency since one row can be represented as a linear combination of the other two

2