<a href="https://colab.research.google.com/github/tombackert/ml-stuff/blob/main/linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
A = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1]])

B = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [ ]:
A * B

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [ ]:
A + B

array([[ 2,  2,  3],
       [ 4,  6,  6],
       [ 7,  8, 10]])

In [ ]:
# transposing a matrix
C1 = np.array([[2, 2],
               [3, 3],
               [4, 4]])

C2 = np.array([[2, 2, 2],
               [3, 3, 3]])

In [ ]:
C1, C2

(array([[2, 2],
        [3, 3],
        [4, 4]]),
 array([[2, 2, 2],
        [3, 3, 3]]))

In [ ]:
C1.T, C2.T

(array([[2, 3, 4],
        [2, 3, 4]]),
 array([[2, 3],
        [2, 3],
        [2, 3]]))

In [ ]:
# transposing a vector
# vector = matrix with onely one column
v1 = np.array([1, 2, 3])
v2 = np.array([[1],
               [2],
               [3]])

In [ ]:
v1, v2

(array([1, 2, 3]),
 array([[1],
        [2],
        [3]]))

In [ ]:
v1.T, v2.T

(array([1, 2, 3]), array([[1, 2, 3]]))

In [ ]:
# scalar multiplikation
# scalar = matrix with only one entry
a1 = np.array([2])
a2 = np.array([2])
a1.T

array([2])

In [ ]:
A = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1]])

B = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [ ]:
C = A + B
C

array([[ 2,  2,  3],
       [ 4,  6,  6],
       [ 7,  8, 10]])

In [ ]:
D = a1 * B + a2
D

array([[ 4,  6,  8],
       [10, 12, 14],
       [16, 18, 20]])

In [ ]:
# Multiplying Matrices and Vectors
E3 = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1]])

A = np.array([[1, 1, 1],
              [1, 1, 1],
              [1, 1, 1]])

B = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [ ]:
C1 = A * B
C2 = E3 * B
C1, C2

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[1, 0, 0],
        [0, 5, 0],
        [0, 0, 9]]))

In [ ]:
#3 x 3
A = np.array([[1, 1, 1],
              [1, 1, 1],
              [1, 1, 1]])

A2 = np.array([[2, 2, 2],
               [2, 2, 2],
               [2, 2, 2]])

A3 = np.array([[3, 3, 3],
               [3, 3, 3],
               [3, 3, 3]])

#2 x 3
B1 = np.array([[1, 2, 3],
               [4, 5, 6]])

#3 x 2
B2 = np.array([[1, 2],
               [4, 5],
               [7, 8]])

C = np.array([[2, 2, 2],
              [3, 3, 3],
              [4, 4, 4]])

C2 = np.array([[2, 3, 4],
               [2, 3, 4],
               [2, 3, 4]])


In [ ]:
C.T

array([[2, 3, 4],
       [2, 3, 4],
       [2, 3, 4]])

In [ ]:
# m x n @ n x p -> m x p
C = A @ B2 # 3 x 3 @ 3 x 2 -> 3 x 2
C

array([[12, 15],
       [12, 15],
       [12, 15]])

In [ ]:
# dot product
x = np.array([1, 1, 1])

y = np.array([1, 4, 7])
y2 = np.array([2, 5, 8])

dot_product1 = np.dot(x, y)
dot_product2 = np.dot(x, y2)

dot_product1, dot_product2

(12, 15)

In [ ]:
# matrix mul is distributive
D1 = A2 @ (A + A3)
D2 = A2 @ A + A2 @ A3
D1, D2

(array([[24, 24, 24],
        [24, 24, 24],
        [24, 24, 24]]),
 array([[24, 24, 24],
        [24, 24, 24],
        [24, 24, 24]]))

In [ ]:
# matrix mul is associative
D1 = A2 @ (A @ A3)
D2 = (A2 @ A) @ A3
D1, D2

(array([[54, 54, 54],
        [54, 54, 54],
        [54, 54, 54]]),
 array([[54, 54, 54],
        [54, 54, 54],
        [54, 54, 54]]))

In [ ]:
# matrix mul is not commutative
D1 = C @ C2
D2 = C2 @ C
D1, D2

(array([[12, 18, 24],
        [18, 27, 36],
        [24, 36, 48]]),
 array([[29, 29, 29],
        [29, 29, 29],
        [29, 29, 29]]))

In [175]:
# Identity and Inverse Matrix
D = np.array([[1, 0, 0],
              [0, 2, 0],
              [0, 0, 4]])

In [162]:
# determinat
det_D = np.linalg.det(D)
det_D

7.999999999999998

In [181]:
# inverse
D_inv = np.linalg.inv(D)
D_inv

array([[1.  , 0.  , 0.  ],
       [0.  , 0.5 , 0.  ],
       [0.  , 0.  , 0.25]])

In [180]:
# D_inv @ D -> I
I = D_inv @ D
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [146]:
# linear dependency
B = np.matrix([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
B.shape

(3, 3)

In [147]:
# A matrix is considered to have linearly dependent rows if its rank is less than the number of rows.
np.linalg.matrix_rank(B) # rank of B is 2 < number of rows -> linear dependency since one row can be represented as a linear combination of the other two

2